/**
 * Generic hook factories.
 *
 * These are the runtime implementations. The actual typed hooks for each model
 * are generated by codegen (Phase 4). These factories provide the DRY core logic.
 */
import {
  useQuery, useMutation, useInfiniteQuery, useQueryClient,
  type UseQueryOptions, type UseMutationOptions, type UseInfiniteQueryOptions,
  type QueryClient,
  keepPreviousData,
} from '@tanstack/react-query'
import type { ModelCacheKeys, ModelIndexResult, PaginationMeta } from './client-model.js'

// ── Search state ──────────────────────────────────────────────────────────────

export interface SearchState {
  scopes?: string[]
  filters?: Record<string, any>
  sort?: { field: string; dir: 'asc' | 'desc' }
  page?: number
  perPage?: number
  [paramScope: string]: any
}

export type SearchSetter<T extends SearchState = SearchState> = (updates: Partial<T>) => void

export interface UseSearchReturn<T extends SearchState = SearchState> {
  state: T
  set: SearchSetter<T>
  reset: () => void
  setScope: (scope: string, active: boolean) => void
  setFilter: (field: string, value: any) => void
  setSort: (field: string, dir?: 'asc' | 'desc') => void
  setPage: (page: number) => void
  setParamScope: (name: string, value: any) => void
}

// ── CRUD hook factory ─────────────────────────────────────────────────────────

export interface CrudHookConfig<TModel, TScopes extends Record<string, number>> {
  keys: ModelCacheKeys<TScopes>
  /** Calls the oRPC index procedure */
  indexFn: (scopes: TScopes, params: SearchState) => Promise<ModelIndexResult<TModel>>
  /** Calls the oRPC get procedure */
  getFn: (id: number | string, scopes: TScopes) => Promise<TModel>
  /** Calls the oRPC create procedure */
  createFn: (scopes: TScopes, data: any) => Promise<TModel>
  /** Calls the oRPC update procedure */
  updateFn: (id: number | string, scopes: TScopes, data: any) => Promise<TModel>
  /** Calls the oRPC destroy procedure */
  destroyFn: (id: number | string, scopes: TScopes) => Promise<void>
  /** Calls a @mutation procedure */
  mutationFns?: Record<string, (id: number | string, scopes: TScopes, data?: any) => Promise<any>>
}

export interface IndexReturn<TModel> {
  data: TModel[]
  pagination: PaginationMeta | undefined
  isLoading: boolean
  isFetching: boolean
  error: Error | null
  isEmpty: boolean
}

export interface InfiniteIndexReturn<TModel> {
  items: TModel[]
  pagination: PaginationMeta | undefined
  fetchNextPage: () => void
  hasNextPage: boolean
  isFetchingNextPage: boolean
  isLoading: boolean
}

export interface UseCrudReturn<TModel, _TScopes extends Record<string, number>> {
  useIndex: (params?: SearchState, options?: Record<string, any>) => IndexReturn<TModel>
  useInfiniteIndex: (params?: Omit<SearchState, 'page'>) => InfiniteIndexReturn<TModel>
  useGet: (id: number | string | null | undefined, options?: Record<string, any>) => { data: TModel | undefined; isLoading: boolean; error: Error | null }
  prefetch: (id: number | string) => void
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  useCreate: (options?: Record<string, any>) => any
  useUpdate: (options?: Record<string, any>) => any
  useDestroy: (options?: Record<string, any>) => any
  useMutation: (name: string, options?: Record<string, any>) => any
}

export function createModelHook<TModel, TScopes extends Record<string, number>>(
  config: CrudHookConfig<TModel, TScopes>,
): (scopes: TScopes) => UseCrudReturn<TModel, TScopes> {
  return function useModel(scopes: TScopes): UseCrudReturn<TModel, TScopes> {
    const queryClient = useQueryClient()
    const { keys, indexFn, getFn, createFn, updateFn, destroyFn, mutationFns } = config

    const useIndex = (
      params: SearchState = {},
      options: Partial<UseQueryOptions> = {},
    ) => {
      const query = useQuery({
        queryKey: keys.list(scopes, params),
        queryFn: () => indexFn(scopes, params),
        placeholderData: keepPreviousData,
        ...(options as any),
      })
      const result = query.data as ModelIndexResult<TModel> | undefined
      return {
        data: result?.data ?? [],
        pagination: result?.pagination,
        isLoading: query.isLoading,
        isFetching: query.isFetching,
        error: query.error as Error | null,
        isEmpty: (result?.data ?? []).length === 0,
      }
    }

    const useInfiniteIndex = (params: Omit<SearchState, 'page'> = {}) => {
      const query = useInfiniteQuery({
        queryKey: [...keys.list(scopes, params), 'infinite'],
        queryFn: ({ pageParam = 0 }) => indexFn(scopes, { ...params, page: pageParam as number }),
        initialPageParam: 0,
        getNextPageParam: (lastPage: ModelIndexResult<TModel>) =>
          lastPage.pagination.hasMore ? lastPage.pagination.page + 1 : undefined,
      })
      const pages = query.data?.pages ?? []
      const items = pages.flatMap((p: ModelIndexResult<TModel>) => p.data)
      const lastPagination = pages[pages.length - 1]?.pagination
      return {
        items,
        pagination: lastPagination,
        fetchNextPage: () => query.fetchNextPage(),
        hasNextPage: query.hasNextPage ?? false,
        isFetchingNextPage: query.isFetchingNextPage,
        isLoading: query.isLoading,
      }
    }

    const useGet = (
      id: number | string | null | undefined,
      options: Partial<UseQueryOptions> = {},
    ) => {
      const query = useQuery({
        queryKey: keys.detail(id ?? 0, scopes),
        queryFn: () => getFn(id!, scopes),
        enabled: id != null,
        ...(options as any),
      })
      return {
        data: query.data as TModel | undefined,
        isLoading: query.isLoading,
        error: query.error as Error | null,
      }
    }

    const prefetch = (id: number | string) => {
      queryClient.prefetchQuery({
        queryKey: keys.detail(id, scopes),
        queryFn: () => getFn(id, scopes),
      })
    }

    const useCreate = (options: Partial<UseMutationOptions> = {}) =>
      useMutation({
        mutationFn: (data: any) => createFn(scopes, data),
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: keys.root(scopes) })
        },
        ...(options as any),
      })

    const useUpdate = (options: Partial<UseMutationOptions> = {}) =>
      useMutation({
        mutationFn: ({ id, data }: { id: number | string; data: any }) =>
          updateFn(id, scopes, data),
        onSuccess: (_result: any, variables: { id: number | string }) => {
          queryClient.invalidateQueries({ queryKey: keys.root(scopes) })
          queryClient.invalidateQueries({ queryKey: keys.detail(variables.id, scopes) })
        },
        ...(options as any),
      })

    const useDestroy = (options: Partial<UseMutationOptions> = {}) =>
      useMutation({
        mutationFn: (id: number | string) => destroyFn(id, scopes),
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: keys.root(scopes) })
        },
        ...(options as any),
      })

    const useMutationHook = (name: string, options: Partial<UseMutationOptions> = {}) => {
      const fn = mutationFns?.[name]
      return useMutation({
        mutationFn: ({ id, data }: { id?: number | string; data?: any }) => {
          if (!fn) throw new Error(`Mutation '${name}' not found`)
          return fn(id ?? 0, scopes, data)
        },
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: keys.root(scopes) })
        },
        ...(options as any),
      })
    }

    return {
      useIndex,
      useInfiniteIndex,
      useGet,
      prefetch,
      useCreate,
      useUpdate,
      useDestroy,
      useMutation: useMutationHook,
    }
  }
}

// ── Singleton hook factory ────────────────────────────────────────────────────

export interface SingletonHookConfig<TModel, TScopes extends Record<string, number>> {
  keys: ModelCacheKeys<TScopes>
  getFn: (scopes: TScopes) => Promise<TModel>
  findOrCreateFn?: (scopes: TScopes) => Promise<TModel>
  updateFn: (scopes: TScopes, data: any) => Promise<TModel>
  mutationFns?: Record<string, (scopes: TScopes, data?: any) => Promise<any>>
}

export function createSingletonHook<TModel, TScopes extends Record<string, number>>(
  config: SingletonHookConfig<TModel, TScopes>,
) {
  return function useSingleton(scopes: TScopes) {
    const queryClient = useQueryClient()
    const { keys, getFn, findOrCreateFn, updateFn, mutationFns } = config

    const useGet = (options: Partial<UseQueryOptions> = {}) => {
      const query = useQuery({
        queryKey: keys.singleton(scopes),
        queryFn: () => getFn(scopes),
        ...(options as any),
      })
      return {
        data: query.data as TModel | undefined,
        isLoading: query.isLoading,
        error: query.error as Error | null,
      }
    }

    const useFindOrCreate = (options: Partial<UseQueryOptions> = {}) => {
      const query = useQuery({
        queryKey: keys.singleton(scopes),
        queryFn: () => (findOrCreateFn ? findOrCreateFn(scopes) : getFn(scopes)),
        ...(options as any),
      })
      return {
        data: query.data as TModel | undefined,
        isLoading: query.isLoading,
        error: query.error as Error | null,
      }
    }

    const useUpdate = (options: Partial<UseMutationOptions> = {}) =>
      useMutation({
        mutationFn: (data: any) => updateFn(scopes, data),
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: keys.singleton(scopes) })
        },
        ...(options as any),
      })

    const useMutationHook = (name: string, options: Partial<UseMutationOptions> = {}) => {
      const fn = mutationFns?.[name]
      return useMutation({
        mutationFn: (data?: any) => {
          if (!fn) throw new Error(`Singleton mutation '${name}' not found`)
          return fn(scopes, data)
        },
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: keys.singleton(scopes) })
        },
        ...(options as any),
      })
    }

    return { useGet, useFindOrCreate, useUpdate, useMutation: useMutationHook }
  }
}

// ── Search hook ───────────────────────────────────────────────────────────────

import { useState, useCallback } from 'react'

export function createSearchHook<TState extends SearchState>(
  defaultState: TState,
) {
  return function useSearch(): UseSearchReturn<TState> {
    const [state, setState] = useState<TState>(defaultState)

    const set = useCallback((updates: Partial<TState>) => {
      setState(s => ({ ...s, ...updates }))
    }, [])

    const reset = useCallback(() => setState(defaultState), [])

    const setScope = useCallback((scope: string, active: boolean) => {
      setState(s => {
        const current = s.scopes ?? []
        const next = active
          ? [...current.filter(s => s !== scope), scope]
          : current.filter(s => s !== scope)
        return { ...s, scopes: next, page: 0 }
      })
    }, [])

    const setFilter = useCallback((field: string, value: any) => {
      setState(s => ({
        ...s,
        filters: { ...(s.filters ?? {}), [field]: value },
        page: 0,
      }))
    }, [])

    const setSort = useCallback((field: string, dir: 'asc' | 'desc' = 'asc') => {
      setState(s => ({ ...s, sort: { field, dir }, page: 0 }))
    }, [])

    const setPage = useCallback((page: number) => {
      setState(s => ({ ...s, page }))
    }, [])

    const setParamScope = useCallback((name: string, value: any) => {
      setState(s => ({ ...s, [name]: value, page: 0 }))
    }, [])

    return { state, set, reset, setScope, setFilter, setSort, setPage, setParamScope }
  }
}
